/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsumeItemRequest
 */
export interface ConsumeItemRequest {
    /**
     * Number of units to consume
     * @type {number}
     * @memberof ConsumeItemRequest
     */
    consumeCount: number;
}

/**
 * Check if a given object implements the ConsumeItemRequest interface.
 */
export function instanceOfConsumeItemRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "consumeCount" in value;

    return isInstance;
}

export function ConsumeItemRequestFromJSON(json: any): ConsumeItemRequest {
    return ConsumeItemRequestFromJSONTyped(json, false);
}

export function ConsumeItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumeItemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'consumeCount': json['consume_count'],
    };
}

export function ConsumeItemRequestToJSON(value?: ConsumeItemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'consume_count': value.consumeCount,
    };
}

