/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConvertUserCurrencyRequest
 */
export interface ConvertUserCurrencyRequest {
    /**
     * Amount to convert (DEPRECATED: use amount_64)
     * @type {number}
     * @memberof ConvertUserCurrencyRequest
     */
    amount?: number;
    /**
     * Amount to convert
     * @type {string}
     * @memberof ConvertUserCurrencyRequest
     */
    amount64?: string;
    /**
     * Name of the currency to convert from
     * @type {string}
     * @memberof ConvertUserCurrencyRequest
     */
    fromCurrency: string;
    /**
     * Name of the currency to convert to
     * @type {string}
     * @memberof ConvertUserCurrencyRequest
     */
    toCurrency: string;
}

/**
 * Check if a given object implements the ConvertUserCurrencyRequest interface.
 */
export function instanceOfConvertUserCurrencyRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fromCurrency" in value;
    isInstance = isInstance && "toCurrency" in value;

    return isInstance;
}

export function ConvertUserCurrencyRequestFromJSON(json: any): ConvertUserCurrencyRequest {
    return ConvertUserCurrencyRequestFromJSONTyped(json, false);
}

export function ConvertUserCurrencyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertUserCurrencyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'amount64': !exists(json, 'amount_64') ? undefined : json['amount_64'],
        'fromCurrency': json['from_currency'],
        'toCurrency': json['to_currency'],
    };
}

export function ConvertUserCurrencyRequestToJSON(value?: ConvertUserCurrencyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'amount_64': value.amount64,
        'from_currency': value.fromCurrency,
        'to_currency': value.toCurrency,
    };
}

