/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryUnlockKey } from './InventoryUnlockKey';
import {
    InventoryUnlockKeyFromJSON,
    InventoryUnlockKeyFromJSONTyped,
    InventoryUnlockKeyToJSON,
} from './InventoryUnlockKey';

/**
 * 
 * @export
 * @interface GrantAndOpenContainerRequest
 */
export interface GrantAndOpenContainerRequest {
    /**
     * If true, the user must have the required balance to be granted the container
     * @type {boolean}
     * @memberof GrantAndOpenContainerRequest
     */
    requireBalance?: boolean;
    /**
     * Id of the sub-inventory instance to grant into
     * @type {string}
     * @memberof GrantAndOpenContainerRequest
     */
    subInventoryInstanceId?: string;
    /**
     * 
     * @type {InventoryUnlockKey}
     * @memberof GrantAndOpenContainerRequest
     */
    unlockCost?: InventoryUnlockKey;
}

/**
 * Check if a given object implements the GrantAndOpenContainerRequest interface.
 */
export function instanceOfGrantAndOpenContainerRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GrantAndOpenContainerRequestFromJSON(json: any): GrantAndOpenContainerRequest {
    return GrantAndOpenContainerRequestFromJSONTyped(json, false);
}

export function GrantAndOpenContainerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantAndOpenContainerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requireBalance': !exists(json, 'require_balance') ? undefined : json['require_balance'],
        'subInventoryInstanceId': !exists(json, 'sub_inventory_instance_id') ? undefined : json['sub_inventory_instance_id'],
        'unlockCost': !exists(json, 'unlock_cost') ? undefined : InventoryUnlockKeyFromJSON(json['unlock_cost']),
    };
}

export function GrantAndOpenContainerRequestToJSON(value?: GrantAndOpenContainerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'require_balance': value.requireBalance,
        'sub_inventory_instance_id': value.subInventoryInstanceId,
        'unlock_cost': InventoryUnlockKeyToJSON(value.unlockCost),
    };
}

