/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncrementUserCurrencyRequest
 */
export interface IncrementUserCurrencyRequest {
    /**
     * Amount to grant/consume (DEPRECATED: use delta_64)
     * @type {number}
     * @memberof IncrementUserCurrencyRequest
     */
    delta?: number;
    /**
     * Amount to grant/consume
     * @type {string}
     * @memberof IncrementUserCurrencyRequest
     */
    delta64?: string;
}

/**
 * Check if a given object implements the IncrementUserCurrencyRequest interface.
 */
export function instanceOfIncrementUserCurrencyRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IncrementUserCurrencyRequestFromJSON(json: any): IncrementUserCurrencyRequest {
    return IncrementUserCurrencyRequestFromJSONTyped(json, false);
}

export function IncrementUserCurrencyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncrementUserCurrencyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'delta': !exists(json, 'delta') ? undefined : json['delta'],
        'delta64': !exists(json, 'delta_64') ? undefined : json['delta_64'],
    };
}

export function IncrementUserCurrencyRequestToJSON(value?: IncrementUserCurrencyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'delta': value.delta,
        'delta_64': value.delta64,
    };
}

