/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryUserCurrencyUpdate
 */
export interface InventoryUserCurrencyUpdate {
    /**
     * Name of the currency
     * @type {string}
     * @memberof InventoryUserCurrencyUpdate
     */
    currencyName?: string;
    /**
     * Balance of the currency after update
     * @type {number}
     * @memberof InventoryUserCurrencyUpdate
     */
    currentBalance?: number;
    /**
     * Balance of the currency after update
     * @type {string}
     * @memberof InventoryUserCurrencyUpdate
     */
    currentBalance64?: string;
    /**
     * Balance of the currency before update
     * @type {number}
     * @memberof InventoryUserCurrencyUpdate
     */
    previousBalance?: number;
    /**
     * Balance of the currency before update
     * @type {string}
     * @memberof InventoryUserCurrencyUpdate
     */
    previousBalance64?: string;
}

/**
 * Check if a given object implements the InventoryUserCurrencyUpdate interface.
 */
export function instanceOfInventoryUserCurrencyUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryUserCurrencyUpdateFromJSON(json: any): InventoryUserCurrencyUpdate {
    return InventoryUserCurrencyUpdateFromJSONTyped(json, false);
}

export function InventoryUserCurrencyUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryUserCurrencyUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currencyName': !exists(json, 'currency_name') ? undefined : json['currency_name'],
        'currentBalance': !exists(json, 'current_balance') ? undefined : json['current_balance'],
        'currentBalance64': !exists(json, 'current_balance_64') ? undefined : json['current_balance_64'],
        'previousBalance': !exists(json, 'previous_balance') ? undefined : json['previous_balance'],
        'previousBalance64': !exists(json, 'previous_balance_64') ? undefined : json['previous_balance_64'],
    };
}

export function InventoryUserCurrencyUpdateToJSON(value?: InventoryUserCurrencyUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currency_name': value.currencyName,
        'current_balance': value.currentBalance,
        'current_balance_64': value.currentBalance64,
        'previous_balance': value.previousBalance,
        'previous_balance_64': value.previousBalance64,
    };
}

