/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryGetUserCurrencyStatsResponse
 */
export interface InventoryGetUserCurrencyStatsResponse {
    /**
     * Total earned currency (DEPRECATED: use total_earned_64)
     * @type {number}
     * @memberof InventoryGetUserCurrencyStatsResponse
     */
    totalEarned?: number;
    /**
     * Total earned currency
     * @type {string}
     * @memberof InventoryGetUserCurrencyStatsResponse
     */
    totalEarned64?: string;
    /**
     * Total spent currency (DEPRECATED: use total_spent_64)
     * @type {number}
     * @memberof InventoryGetUserCurrencyStatsResponse
     */
    totalSpent?: number;
    /**
     * Total spent currency
     * @type {string}
     * @memberof InventoryGetUserCurrencyStatsResponse
     */
    totalSpent64?: string;
}

/**
 * Check if a given object implements the InventoryGetUserCurrencyStatsResponse interface.
 */
export function instanceOfInventoryGetUserCurrencyStatsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGetUserCurrencyStatsResponseFromJSON(json: any): InventoryGetUserCurrencyStatsResponse {
    return InventoryGetUserCurrencyStatsResponseFromJSONTyped(json, false);
}

export function InventoryGetUserCurrencyStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGetUserCurrencyStatsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalEarned': !exists(json, 'total_earned') ? undefined : json['total_earned'],
        'totalEarned64': !exists(json, 'total_earned_64') ? undefined : json['total_earned_64'],
        'totalSpent': !exists(json, 'total_spent') ? undefined : json['total_spent'],
        'totalSpent64': !exists(json, 'total_spent_64') ? undefined : json['total_spent_64'],
    };
}

export function InventoryGetUserCurrencyStatsResponseToJSON(value?: InventoryGetUserCurrencyStatsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_earned': value.totalEarned,
        'total_earned_64': value.totalEarned64,
        'total_spent': value.totalSpent,
        'total_spent_64': value.totalSpent64,
    };
}

