/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryApplicableDiscounts } from './InventoryApplicableDiscounts';
import {
    InventoryApplicableDiscountsFromJSON,
    InventoryApplicableDiscountsFromJSONTyped,
    InventoryApplicableDiscountsToJSON,
} from './InventoryApplicableDiscounts';
import type { InventoryAppliedDiscounts } from './InventoryAppliedDiscounts';
import {
    InventoryAppliedDiscountsFromJSON,
    InventoryAppliedDiscountsFromJSONTyped,
    InventoryAppliedDiscountsToJSON,
} from './InventoryAppliedDiscounts';

/**
 * 
 * @export
 * @interface InventoryPurchasableSetting
 */
export interface InventoryPurchasableSetting {
    /**
     * 
     * @type {InventoryAppliedDiscounts}
     * @memberof InventoryPurchasableSetting
     */
    appliedDiscounts?: InventoryAppliedDiscounts;
    /**
     * Currency name
     * @type {string}
     * @memberof InventoryPurchasableSetting
     */
    currency: string;
    /**
     * 
     * @type {InventoryApplicableDiscounts}
     * @memberof InventoryPurchasableSetting
     */
    discounts?: InventoryApplicableDiscounts;
    /**
     * Display price of item (DEPRECATED: use display_price_64)
     * @type {number}
     * @memberof InventoryPurchasableSetting
     */
    displayPrice?: number;
    /**
     * Display price of item
     * @type {string}
     * @memberof InventoryPurchasableSetting
     */
    displayPrice64?: string;
    /**
     * Price of item (DEPRECATED: use price_64)
     * @type {number}
     * @memberof InventoryPurchasableSetting
     */
    price?: number;
    /**
     * Price of item
     * @type {string}
     * @memberof InventoryPurchasableSetting
     */
    price64?: string;
}

/**
 * Check if a given object implements the InventoryPurchasableSetting interface.
 */
export function instanceOfInventoryPurchasableSetting(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "currency" in value;

    return isInstance;
}

export function InventoryPurchasableSettingFromJSON(json: any): InventoryPurchasableSetting {
    return InventoryPurchasableSettingFromJSONTyped(json, false);
}

export function InventoryPurchasableSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryPurchasableSetting {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appliedDiscounts': !exists(json, 'applied_discounts') ? undefined : InventoryAppliedDiscountsFromJSON(json['applied_discounts']),
        'currency': json['currency'],
        'discounts': !exists(json, 'discounts') ? undefined : InventoryApplicableDiscountsFromJSON(json['discounts']),
        'displayPrice': !exists(json, 'display_price') ? undefined : json['display_price'],
        'displayPrice64': !exists(json, 'display_price_64') ? undefined : json['display_price_64'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'price64': !exists(json, 'price_64') ? undefined : json['price_64'],
    };
}

export function InventoryPurchasableSettingToJSON(value?: InventoryPurchasableSetting | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'applied_discounts': InventoryAppliedDiscountsToJSON(value.appliedDiscounts),
        'currency': value.currency,
        'discounts': InventoryApplicableDiscountsToJSON(value.discounts),
        'display_price': value.displayPrice,
        'display_price_64': value.displayPrice64,
        'price': value.price,
        'price_64': value.price64,
    };
}

