/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryGrantResults } from './InventoryGrantResults';
import {
    InventoryGrantResultsFromJSON,
    InventoryGrantResultsFromJSONTyped,
    InventoryGrantResultsToJSON,
} from './InventoryGrantResults';
import type { InventoryUserInventoryItem } from './InventoryUserInventoryItem';
import {
    InventoryUserInventoryItemFromJSON,
    InventoryUserInventoryItemFromJSONTyped,
    InventoryUserInventoryItemToJSON,
} from './InventoryUserInventoryItem';

/**
 * 
 * @export
 * @interface InventoryGrantAndOpenContainerResponse
 */
export interface InventoryGrantAndOpenContainerResponse {
    /**
     * 
     * @type {InventoryGrantResults}
     * @memberof InventoryGrantAndOpenContainerResponse
     */
    grantResults?: InventoryGrantResults;
    /**
     * Items granted to the user (DEPRECATED: use grant_results.granted_items)
     * @type {Array<InventoryUserInventoryItem>}
     * @memberof InventoryGrantAndOpenContainerResponse
     */
    grantedItems?: Array<InventoryUserInventoryItem>;
    /**
     * Trackables energy granted to the user (DEPRECATED: use grant_results.granted_trackables_energy)
     * @type {{ [key: string]: number; }}
     * @memberof InventoryGrantAndOpenContainerResponse
     */
    grantedTrackablesEnergy?: { [key: string]: number; };
    /**
     * Trackables xp granted to the user (DEPRECATED: use grant_results.granted_trackables_xp)
     * @type {{ [key: string]: number; }}
     * @memberof InventoryGrantAndOpenContainerResponse
     */
    grantedTrackablesXp?: { [key: string]: number; };
    /**
     * Virtual currency granted to the user (DEPRECATED: use grant_results.granted_currencies)
     * @type {{ [key: string]: number; }}
     * @memberof InventoryGrantAndOpenContainerResponse
     */
    grantedVirtualCurrency?: { [key: string]: number; };
    /**
     * Virtual currency granted to the user (DEPRECATED: use grant_results.granted_currencies)
     * @type {{ [key: string]: string; }}
     * @memberof InventoryGrantAndOpenContainerResponse
     */
    grantedVirtualCurrency64?: { [key: string]: string; };
}

/**
 * Check if a given object implements the InventoryGrantAndOpenContainerResponse interface.
 */
export function instanceOfInventoryGrantAndOpenContainerResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGrantAndOpenContainerResponseFromJSON(json: any): InventoryGrantAndOpenContainerResponse {
    return InventoryGrantAndOpenContainerResponseFromJSONTyped(json, false);
}

export function InventoryGrantAndOpenContainerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGrantAndOpenContainerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'grantResults': !exists(json, 'grant_results') ? undefined : InventoryGrantResultsFromJSON(json['grant_results']),
        'grantedItems': !exists(json, 'granted_items') ? undefined : ((json['granted_items'] as Array<any>).map(InventoryUserInventoryItemFromJSON)),
        'grantedTrackablesEnergy': !exists(json, 'granted_trackables_energy') ? undefined : json['granted_trackables_energy'],
        'grantedTrackablesXp': !exists(json, 'granted_trackables_xp') ? undefined : json['granted_trackables_xp'],
        'grantedVirtualCurrency': !exists(json, 'granted_virtual_currency') ? undefined : json['granted_virtual_currency'],
        'grantedVirtualCurrency64': !exists(json, 'granted_virtual_currency_64') ? undefined : json['granted_virtual_currency_64'],
    };
}

export function InventoryGrantAndOpenContainerResponseToJSON(value?: InventoryGrantAndOpenContainerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'grant_results': InventoryGrantResultsToJSON(value.grantResults),
        'granted_items': value.grantedItems === undefined ? undefined : ((value.grantedItems as Array<any>).map(InventoryUserInventoryItemToJSON)),
        'granted_trackables_energy': value.grantedTrackablesEnergy,
        'granted_trackables_xp': value.grantedTrackablesXp,
        'granted_virtual_currency': value.grantedVirtualCurrency,
        'granted_virtual_currency_64': value.grantedVirtualCurrency64,
    };
}

