/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryApplicableDiscounts
 */
export interface InventoryApplicableDiscounts {
    /**
     * List of applicable discount ids
     * @type {Array<string>}
     * @memberof InventoryApplicableDiscounts
     */
    discountNames?: Array<string>;
    /**
     * Minimum price after applying discounts
     * @type {number}
     * @memberof InventoryApplicableDiscounts
     */
    floorPrice?: number;
    /**
     * Strategy used to apply discounts
     * @type {string}
     * @memberof InventoryApplicableDiscounts
     */
    strategy?: string;
}

/**
 * Check if a given object implements the InventoryApplicableDiscounts interface.
 */
export function instanceOfInventoryApplicableDiscounts(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryApplicableDiscountsFromJSON(json: any): InventoryApplicableDiscounts {
    return InventoryApplicableDiscountsFromJSONTyped(json, false);
}

export function InventoryApplicableDiscountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryApplicableDiscounts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discountNames': !exists(json, 'discount_names') ? undefined : json['discount_names'],
        'floorPrice': !exists(json, 'floor_price') ? undefined : json['floor_price'],
        'strategy': !exists(json, 'strategy') ? undefined : json['strategy'],
    };
}

export function InventoryApplicableDiscountsToJSON(value?: InventoryApplicableDiscounts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discount_names': value.discountNames,
        'floor_price': value.floorPrice,
        'strategy': value.strategy,
    };
}

