/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryGrantedCurrency
 */
export interface InventoryGrantedCurrency {
    /**
     * Balance of the currency after granting (DEPRECATED: use after_balance_64)
     * @type {number}
     * @memberof InventoryGrantedCurrency
     */
    afterBalance?: number;
    /**
     * Balance of the currency after granting
     * @type {string}
     * @memberof InventoryGrantedCurrency
     */
    afterBalance64?: string;
    /**
     * Balance of the currency before granting (DEPRECATED: use before_balance_64)
     * @type {number}
     * @memberof InventoryGrantedCurrency
     */
    beforeBalance?: number;
    /**
     * Balance of the currency before granting
     * @type {string}
     * @memberof InventoryGrantedCurrency
     */
    beforeBalance64?: string;
    /**
     * Name of the currency granted
     * @type {string}
     * @memberof InventoryGrantedCurrency
     */
    currencyName?: string;
}

/**
 * Check if a given object implements the InventoryGrantedCurrency interface.
 */
export function instanceOfInventoryGrantedCurrency(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGrantedCurrencyFromJSON(json: any): InventoryGrantedCurrency {
    return InventoryGrantedCurrencyFromJSONTyped(json, false);
}

export function InventoryGrantedCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGrantedCurrency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'afterBalance': !exists(json, 'after_balance') ? undefined : json['after_balance'],
        'afterBalance64': !exists(json, 'after_balance_64') ? undefined : json['after_balance_64'],
        'beforeBalance': !exists(json, 'before_balance') ? undefined : json['before_balance'],
        'beforeBalance64': !exists(json, 'before_balance_64') ? undefined : json['before_balance_64'],
        'currencyName': !exists(json, 'currency_name') ? undefined : json['currency_name'],
    };
}

export function InventoryGrantedCurrencyToJSON(value?: InventoryGrantedCurrency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'after_balance': value.afterBalance,
        'after_balance_64': value.afterBalance64,
        'before_balance': value.beforeBalance,
        'before_balance_64': value.beforeBalance64,
        'currency_name': value.currencyName,
    };
}

