/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryApplicableDiscounts } from './InventoryApplicableDiscounts';
import {
    InventoryApplicableDiscountsFromJSON,
    InventoryApplicableDiscountsFromJSONTyped,
    InventoryApplicableDiscountsToJSON,
} from './InventoryApplicableDiscounts';
import type { InventoryAppliedDiscounts } from './InventoryAppliedDiscounts';
import {
    InventoryAppliedDiscountsFromJSON,
    InventoryAppliedDiscountsFromJSONTyped,
    InventoryAppliedDiscountsToJSON,
} from './InventoryAppliedDiscounts';
import type { InventoryUnlockCostType } from './InventoryUnlockCostType';
import {
    InventoryUnlockCostTypeFromJSON,
    InventoryUnlockCostTypeFromJSONTyped,
    InventoryUnlockCostTypeToJSON,
} from './InventoryUnlockCostType';

/**
 * 
 * @export
 * @interface InventoryUnlockCost
 */
export interface InventoryUnlockCost {
    /**
     * 
     * @type {InventoryAppliedDiscounts}
     * @memberof InventoryUnlockCost
     */
    appliedDiscounts?: InventoryAppliedDiscounts;
    /**
     * Count of the item/currency/trackable_energy (DEPRECATED: use count_64)
     * @type {number}
     * @memberof InventoryUnlockCost
     */
    count?: number;
    /**
     * Count of the item/currency/trackable_energy
     * @type {number}
     * @memberof InventoryUnlockCost
     */
    count64?: number;
    /**
     * 
     * @type {InventoryApplicableDiscounts}
     * @memberof InventoryUnlockCost
     */
    discounts?: InventoryApplicableDiscounts;
    /**
     * Name of the item/currency/trackable_energy
     * @type {string}
     * @memberof InventoryUnlockCost
     */
    name: string;
    /**
     * 
     * @type {InventoryUnlockCostType}
     * @memberof InventoryUnlockCost
     */
    type: InventoryUnlockCostType;
}

/**
 * Check if a given object implements the InventoryUnlockCost interface.
 */
export function instanceOfInventoryUnlockCost(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function InventoryUnlockCostFromJSON(json: any): InventoryUnlockCost {
    return InventoryUnlockCostFromJSONTyped(json, false);
}

export function InventoryUnlockCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryUnlockCost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appliedDiscounts': !exists(json, 'applied_discounts') ? undefined : InventoryAppliedDiscountsFromJSON(json['applied_discounts']),
        'count': !exists(json, 'count') ? undefined : json['count'],
        'count64': !exists(json, 'count_64') ? undefined : json['count_64'],
        'discounts': !exists(json, 'discounts') ? undefined : InventoryApplicableDiscountsFromJSON(json['discounts']),
        'name': json['name'],
        'type': InventoryUnlockCostTypeFromJSON(json['type']),
    };
}

export function InventoryUnlockCostToJSON(value?: InventoryUnlockCost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'applied_discounts': InventoryAppliedDiscountsToJSON(value.appliedDiscounts),
        'count': value.count,
        'count_64': value.count64,
        'discounts': InventoryApplicableDiscountsToJSON(value.discounts),
        'name': value.name,
        'type': InventoryUnlockCostTypeToJSON(value.type),
    };
}

