/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryConsumable
 */
export interface InventoryConsumable {
    /**
     * True if item is consumable
     * @type {boolean}
     * @memberof InventoryConsumable
     */
    isConsumable: boolean;
}

/**
 * Check if a given object implements the InventoryConsumable interface.
 */
export function instanceOfInventoryConsumable(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isConsumable" in value;

    return isInstance;
}

export function InventoryConsumableFromJSON(json: any): InventoryConsumable {
    return InventoryConsumableFromJSONTyped(json, false);
}

export function InventoryConsumableFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryConsumable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isConsumable': json['is_consumable'],
    };
}

export function InventoryConsumableToJSON(value?: InventoryConsumable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_consumable': value.isConsumable,
    };
}

