/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryPurchasableSetting } from './InventoryPurchasableSetting';
import {
    InventoryPurchasableSettingFromJSON,
    InventoryPurchasableSettingFromJSONTyped,
    InventoryPurchasableSettingToJSON,
} from './InventoryPurchasableSetting';

/**
 * 
 * @export
 * @interface InventoryPurchasable
 */
export interface InventoryPurchasable {
    /**
     * 
     * @type {Array<InventoryPurchasableSetting>}
     * @memberof InventoryPurchasable
     */
    settings?: Array<InventoryPurchasableSetting>;
}

/**
 * Check if a given object implements the InventoryPurchasable interface.
 */
export function instanceOfInventoryPurchasable(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryPurchasableFromJSON(json: any): InventoryPurchasable {
    return InventoryPurchasableFromJSONTyped(json, false);
}

export function InventoryPurchasableFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryPurchasable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'settings': !exists(json, 'settings') ? undefined : ((json['settings'] as Array<any>).map(InventoryPurchasableSettingFromJSON)),
    };
}

export function InventoryPurchasableToJSON(value?: InventoryPurchasable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'settings': value.settings === undefined ? undefined : ((value.settings as Array<any>).map(InventoryPurchasableSettingToJSON)),
    };
}

