/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryIncrementUserCurrencyResponse
 */
export interface InventoryIncrementUserCurrencyResponse {
    /**
     * Current Balance of given currency with user after adding (DEPRECATED: use current_balance_64)
     * @type {number}
     * @memberof InventoryIncrementUserCurrencyResponse
     */
    currentBalance?: number;
    /**
     * Current Balance of given currency with user after adding
     * @type {string}
     * @memberof InventoryIncrementUserCurrencyResponse
     */
    currentBalance64?: string;
    /**
     * Balance of given currency with user before adding (DEPRECATED: use previous_balance_64)
     * @type {number}
     * @memberof InventoryIncrementUserCurrencyResponse
     */
    previousBalance?: number;
    /**
     * Balance of given currency with user before adding
     * @type {string}
     * @memberof InventoryIncrementUserCurrencyResponse
     */
    previousBalance64?: string;
}

/**
 * Check if a given object implements the InventoryIncrementUserCurrencyResponse interface.
 */
export function instanceOfInventoryIncrementUserCurrencyResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryIncrementUserCurrencyResponseFromJSON(json: any): InventoryIncrementUserCurrencyResponse {
    return InventoryIncrementUserCurrencyResponseFromJSONTyped(json, false);
}

export function InventoryIncrementUserCurrencyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryIncrementUserCurrencyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentBalance': !exists(json, 'current_balance') ? undefined : json['current_balance'],
        'currentBalance64': !exists(json, 'current_balance_64') ? undefined : json['current_balance_64'],
        'previousBalance': !exists(json, 'previous_balance') ? undefined : json['previous_balance'],
        'previousBalance64': !exists(json, 'previous_balance_64') ? undefined : json['previous_balance_64'],
    };
}

export function InventoryIncrementUserCurrencyResponseToJSON(value?: InventoryIncrementUserCurrencyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current_balance': value.currentBalance,
        'current_balance_64': value.currentBalance64,
        'previous_balance': value.previousBalance,
        'previous_balance_64': value.previousBalance64,
    };
}

