/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const InventoryUnlockCostType = {
    UnspecifiedType: 'UNSPECIFIED_TYPE',
    Item: 'ITEM',
    Currency: 'CURRENCY',
    Energy: 'ENERGY'
} as const;
export type InventoryUnlockCostType = typeof InventoryUnlockCostType[keyof typeof InventoryUnlockCostType];


export function InventoryUnlockCostTypeFromJSON(json: any): InventoryUnlockCostType {
    return InventoryUnlockCostTypeFromJSONTyped(json, false);
}

export function InventoryUnlockCostTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryUnlockCostType {
    return json as InventoryUnlockCostType;
}

export function InventoryUnlockCostTypeToJSON(value?: InventoryUnlockCostType | null): any {
    return value as any;
}

