/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryUserCurrencyUpdate } from './InventoryUserCurrencyUpdate';
import {
    InventoryUserCurrencyUpdateFromJSON,
    InventoryUserCurrencyUpdateFromJSONTyped,
    InventoryUserCurrencyUpdateToJSON,
} from './InventoryUserCurrencyUpdate';

/**
 * 
 * @export
 * @interface InventoryConvertUserCurrencyResponse
 */
export interface InventoryConvertUserCurrencyResponse {
    /**
     * 
     * @type {InventoryUserCurrencyUpdate}
     * @memberof InventoryConvertUserCurrencyResponse
     */
    fromCurrency?: InventoryUserCurrencyUpdate;
    /**
     * 
     * @type {InventoryUserCurrencyUpdate}
     * @memberof InventoryConvertUserCurrencyResponse
     */
    toCurrency?: InventoryUserCurrencyUpdate;
}

/**
 * Check if a given object implements the InventoryConvertUserCurrencyResponse interface.
 */
export function instanceOfInventoryConvertUserCurrencyResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryConvertUserCurrencyResponseFromJSON(json: any): InventoryConvertUserCurrencyResponse {
    return InventoryConvertUserCurrencyResponseFromJSONTyped(json, false);
}

export function InventoryConvertUserCurrencyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryConvertUserCurrencyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromCurrency': !exists(json, 'from_currency') ? undefined : InventoryUserCurrencyUpdateFromJSON(json['from_currency']),
        'toCurrency': !exists(json, 'to_currency') ? undefined : InventoryUserCurrencyUpdateFromJSON(json['to_currency']),
    };
}

export function InventoryConvertUserCurrencyResponseToJSON(value?: InventoryConvertUserCurrencyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from_currency': InventoryUserCurrencyUpdateToJSON(value.fromCurrency),
        'to_currency': InventoryUserCurrencyUpdateToJSON(value.toCurrency),
    };
}

