/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryEvaluateDropTableResponse
 */
export interface InventoryEvaluateDropTableResponse {
    /**
     * Virtual currencies that will be granted to the user (DEPRECATED: use currencies_64)
     * @type {{ [key: string]: number; }}
     * @memberof InventoryEvaluateDropTableResponse
     */
    currencies?: { [key: string]: number; };
    /**
     * Virtual currencies that will be granted to the user
     * @type {{ [key: string]: string; }}
     * @memberof InventoryEvaluateDropTableResponse
     */
    currencies64?: { [key: string]: string; };
    /**
     * Index of the drop table that was evaluated
     * @type {number}
     * @memberof InventoryEvaluateDropTableResponse
     */
    dropIndex?: number;
    /**
     * Escrow id for the result
     * @type {string}
     * @memberof InventoryEvaluateDropTableResponse
     */
    escrowId?: string;
    /**
     * Items that will be granted to the user
     * @type {{ [key: string]: number; }}
     * @memberof InventoryEvaluateDropTableResponse
     */
    items?: { [key: string]: number; };
    /**
     * Trackables energies to be granted to the user
     * @type {{ [key: string]: number; }}
     * @memberof InventoryEvaluateDropTableResponse
     */
    trackablesEnergy?: { [key: string]: number; };
    /**
     * Trackables xps to be granted to the user
     * @type {{ [key: string]: number; }}
     * @memberof InventoryEvaluateDropTableResponse
     */
    trackablesXp?: { [key: string]: number; };
}

/**
 * Check if a given object implements the InventoryEvaluateDropTableResponse interface.
 */
export function instanceOfInventoryEvaluateDropTableResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryEvaluateDropTableResponseFromJSON(json: any): InventoryEvaluateDropTableResponse {
    return InventoryEvaluateDropTableResponseFromJSONTyped(json, false);
}

export function InventoryEvaluateDropTableResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryEvaluateDropTableResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currencies': !exists(json, 'currencies') ? undefined : json['currencies'],
        'currencies64': !exists(json, 'currencies_64') ? undefined : json['currencies_64'],
        'dropIndex': !exists(json, 'drop_index') ? undefined : json['drop_index'],
        'escrowId': !exists(json, 'escrow_id') ? undefined : json['escrow_id'],
        'items': !exists(json, 'items') ? undefined : json['items'],
        'trackablesEnergy': !exists(json, 'trackables_energy') ? undefined : json['trackables_energy'],
        'trackablesXp': !exists(json, 'trackables_xp') ? undefined : json['trackables_xp'],
    };
}

export function InventoryEvaluateDropTableResponseToJSON(value?: InventoryEvaluateDropTableResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currencies': value.currencies,
        'currencies_64': value.currencies64,
        'drop_index': value.dropIndex,
        'escrow_id': value.escrowId,
        'items': value.items,
        'trackables_energy': value.trackablesEnergy,
        'trackables_xp': value.trackablesXp,
    };
}

