/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryGrantedTrackablesEnergy
 */
export interface InventoryGrantedTrackablesEnergy {
    /**
     * Energy of the user after granting
     * @type {number}
     * @memberof InventoryGrantedTrackablesEnergy
     */
    afterEnergy?: number;
    /**
     * Energy of the user before granting
     * @type {number}
     * @memberof InventoryGrantedTrackablesEnergy
     */
    beforeEnergy?: number;
    /**
     * Name of the trackable energy granted
     * @type {string}
     * @memberof InventoryGrantedTrackablesEnergy
     */
    trackableEnergyName?: string;
}

/**
 * Check if a given object implements the InventoryGrantedTrackablesEnergy interface.
 */
export function instanceOfInventoryGrantedTrackablesEnergy(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGrantedTrackablesEnergyFromJSON(json: any): InventoryGrantedTrackablesEnergy {
    return InventoryGrantedTrackablesEnergyFromJSONTyped(json, false);
}

export function InventoryGrantedTrackablesEnergyFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGrantedTrackablesEnergy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'afterEnergy': !exists(json, 'after_energy') ? undefined : json['after_energy'],
        'beforeEnergy': !exists(json, 'before_energy') ? undefined : json['before_energy'],
        'trackableEnergyName': !exists(json, 'trackable_energy_name') ? undefined : json['trackable_energy_name'],
    };
}

export function InventoryGrantedTrackablesEnergyToJSON(value?: InventoryGrantedTrackablesEnergy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'after_energy': value.afterEnergy,
        'before_energy': value.beforeEnergy,
        'trackable_energy_name': value.trackableEnergyName,
    };
}

