/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryMoveItemsToSubInventoryResponse
 */
export interface InventoryMoveItemsToSubInventoryResponse {
    /**
     * True if the move was successful
     * @type {boolean}
     * @memberof InventoryMoveItemsToSubInventoryResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the InventoryMoveItemsToSubInventoryResponse interface.
 */
export function instanceOfInventoryMoveItemsToSubInventoryResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryMoveItemsToSubInventoryResponseFromJSON(json: any): InventoryMoveItemsToSubInventoryResponse {
    return InventoryMoveItemsToSubInventoryResponseFromJSONTyped(json, false);
}

export function InventoryMoveItemsToSubInventoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryMoveItemsToSubInventoryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function InventoryMoveItemsToSubInventoryResponseToJSON(value?: InventoryMoveItemsToSubInventoryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

