/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryGrantedCurrency } from './InventoryGrantedCurrency';
import {
    InventoryGrantedCurrencyFromJSON,
    InventoryGrantedCurrencyFromJSONTyped,
    InventoryGrantedCurrencyToJSON,
} from './InventoryGrantedCurrency';
import type { InventoryGrantedItem } from './InventoryGrantedItem';
import {
    InventoryGrantedItemFromJSON,
    InventoryGrantedItemFromJSONTyped,
    InventoryGrantedItemToJSON,
} from './InventoryGrantedItem';
import type { InventoryGrantedTrackablesEnergy } from './InventoryGrantedTrackablesEnergy';
import {
    InventoryGrantedTrackablesEnergyFromJSON,
    InventoryGrantedTrackablesEnergyFromJSONTyped,
    InventoryGrantedTrackablesEnergyToJSON,
} from './InventoryGrantedTrackablesEnergy';
import type { InventoryGrantedTrackablesXp } from './InventoryGrantedTrackablesXp';
import {
    InventoryGrantedTrackablesXpFromJSON,
    InventoryGrantedTrackablesXpFromJSONTyped,
    InventoryGrantedTrackablesXpToJSON,
} from './InventoryGrantedTrackablesXp';

/**
 * 
 * @export
 * @interface InventoryGrantResults
 */
export interface InventoryGrantResults {
    /**
     * Virtual currencies granted to the user
     * @type {Array<InventoryGrantedCurrency>}
     * @memberof InventoryGrantResults
     */
    grantedCurrencies?: Array<InventoryGrantedCurrency>;
    /**
     * Items granted to the user
     * @type {Array<InventoryGrantedItem>}
     * @memberof InventoryGrantResults
     */
    grantedItems?: Array<InventoryGrantedItem>;
    /**
     * Trackables energy granted to the user
     * @type {Array<InventoryGrantedTrackablesEnergy>}
     * @memberof InventoryGrantResults
     */
    grantedTrackablesEnergy?: Array<InventoryGrantedTrackablesEnergy>;
    /**
     * Trackables xp granted to the user
     * @type {Array<InventoryGrantedTrackablesXp>}
     * @memberof InventoryGrantResults
     */
    grantedTrackablesXp?: Array<InventoryGrantedTrackablesXp>;
}

/**
 * Check if a given object implements the InventoryGrantResults interface.
 */
export function instanceOfInventoryGrantResults(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGrantResultsFromJSON(json: any): InventoryGrantResults {
    return InventoryGrantResultsFromJSONTyped(json, false);
}

export function InventoryGrantResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGrantResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'grantedCurrencies': !exists(json, 'granted_currencies') ? undefined : ((json['granted_currencies'] as Array<any>).map(InventoryGrantedCurrencyFromJSON)),
        'grantedItems': !exists(json, 'granted_items') ? undefined : ((json['granted_items'] as Array<any>).map(InventoryGrantedItemFromJSON)),
        'grantedTrackablesEnergy': !exists(json, 'granted_trackables_energy') ? undefined : ((json['granted_trackables_energy'] as Array<any>).map(InventoryGrantedTrackablesEnergyFromJSON)),
        'grantedTrackablesXp': !exists(json, 'granted_trackables_xp') ? undefined : ((json['granted_trackables_xp'] as Array<any>).map(InventoryGrantedTrackablesXpFromJSON)),
    };
}

export function InventoryGrantResultsToJSON(value?: InventoryGrantResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'granted_currencies': value.grantedCurrencies === undefined ? undefined : ((value.grantedCurrencies as Array<any>).map(InventoryGrantedCurrencyToJSON)),
        'granted_items': value.grantedItems === undefined ? undefined : ((value.grantedItems as Array<any>).map(InventoryGrantedItemToJSON)),
        'granted_trackables_energy': value.grantedTrackablesEnergy === undefined ? undefined : ((value.grantedTrackablesEnergy as Array<any>).map(InventoryGrantedTrackablesEnergyToJSON)),
        'granted_trackables_xp': value.grantedTrackablesXp === undefined ? undefined : ((value.grantedTrackablesXp as Array<any>).map(InventoryGrantedTrackablesXpToJSON)),
    };
}

