/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryCurrencyConversion
 */
export interface InventoryCurrencyConversion {
    /**
     * Name of currency to convert from
     * @type {string}
     * @memberof InventoryCurrencyConversion
     */
    fromCurrency?: string;
    /**
     * Multiplier for from_currency (DEPRECATED: use multiplier_64)
     * @type {number}
     * @memberof InventoryCurrencyConversion
     */
    multiplier?: number;
    /**
     * Multiplier for from_currency
     * @type {number}
     * @memberof InventoryCurrencyConversion
     */
    multiplier64?: number;
    /**
     * Name of currency to convert to
     * @type {string}
     * @memberof InventoryCurrencyConversion
     */
    toCurrency?: string;
}

/**
 * Check if a given object implements the InventoryCurrencyConversion interface.
 */
export function instanceOfInventoryCurrencyConversion(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryCurrencyConversionFromJSON(json: any): InventoryCurrencyConversion {
    return InventoryCurrencyConversionFromJSONTyped(json, false);
}

export function InventoryCurrencyConversionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryCurrencyConversion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromCurrency': !exists(json, 'from_currency') ? undefined : json['from_currency'],
        'multiplier': !exists(json, 'multiplier') ? undefined : json['multiplier'],
        'multiplier64': !exists(json, 'multiplier_64') ? undefined : json['multiplier_64'],
        'toCurrency': !exists(json, 'to_currency') ? undefined : json['to_currency'],
    };
}

export function InventoryCurrencyConversionToJSON(value?: InventoryCurrencyConversion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from_currency': value.fromCurrency,
        'multiplier': value.multiplier,
        'multiplier_64': value.multiplier64,
        'to_currency': value.toCurrency,
    };
}

