/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryGetUserCurrenciesResponse
 */
export interface InventoryGetUserCurrenciesResponse {
    /**
     * Map of currency name to balance (DEPRECATED: use currencies_64)
     * @type {{ [key: string]: number; }}
     * @memberof InventoryGetUserCurrenciesResponse
     */
    currencies?: { [key: string]: number; };
    /**
     * Map of currency name to balance
     * @type {{ [key: string]: string; }}
     * @memberof InventoryGetUserCurrenciesResponse
     */
    currencies64?: { [key: string]: string; };
}

/**
 * Check if a given object implements the InventoryGetUserCurrenciesResponse interface.
 */
export function instanceOfInventoryGetUserCurrenciesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGetUserCurrenciesResponseFromJSON(json: any): InventoryGetUserCurrenciesResponse {
    return InventoryGetUserCurrenciesResponseFromJSONTyped(json, false);
}

export function InventoryGetUserCurrenciesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGetUserCurrenciesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currencies': !exists(json, 'currencies') ? undefined : json['currencies'],
        'currencies64': !exists(json, 'currencies_64') ? undefined : json['currencies_64'],
    };
}

export function InventoryGetUserCurrenciesResponseToJSON(value?: InventoryGetUserCurrenciesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currencies': value.currencies,
        'currencies_64': value.currencies64,
    };
}

