/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryBatchGetUserItemsSingleResponse } from './InventoryBatchGetUserItemsSingleResponse';
import {
    InventoryBatchGetUserItemsSingleResponseFromJSON,
    InventoryBatchGetUserItemsSingleResponseFromJSONTyped,
    InventoryBatchGetUserItemsSingleResponseToJSON,
} from './InventoryBatchGetUserItemsSingleResponse';

/**
 * 
 * @export
 * @interface InventoryBatchGetUserItemsResponse
 */
export interface InventoryBatchGetUserItemsResponse {
    /**
     * 
     * @type {Array<InventoryBatchGetUserItemsSingleResponse>}
     * @memberof InventoryBatchGetUserItemsResponse
     */
    responses?: Array<InventoryBatchGetUserItemsSingleResponse>;
}

/**
 * Check if a given object implements the InventoryBatchGetUserItemsResponse interface.
 */
export function instanceOfInventoryBatchGetUserItemsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryBatchGetUserItemsResponseFromJSON(json: any): InventoryBatchGetUserItemsResponse {
    return InventoryBatchGetUserItemsResponseFromJSONTyped(json, false);
}

export function InventoryBatchGetUserItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryBatchGetUserItemsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'responses': !exists(json, 'responses') ? undefined : ((json['responses'] as Array<any>).map(InventoryBatchGetUserItemsSingleResponseFromJSON)),
    };
}

export function InventoryBatchGetUserItemsResponseToJSON(value?: InventoryBatchGetUserItemsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'responses': value.responses === undefined ? undefined : ((value.responses as Array<any>).map(InventoryBatchGetUserItemsSingleResponseToJSON)),
    };
}

