/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryGetTotalCurrencyResponse
 */
export interface InventoryGetTotalCurrencyResponse {
    /**
     * 
     * @type {number}
     * @memberof InventoryGetTotalCurrencyResponse
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof InventoryGetTotalCurrencyResponse
     */
    total64?: string;
}

/**
 * Check if a given object implements the InventoryGetTotalCurrencyResponse interface.
 */
export function instanceOfInventoryGetTotalCurrencyResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGetTotalCurrencyResponseFromJSON(json: any): InventoryGetTotalCurrencyResponse {
    return InventoryGetTotalCurrencyResponseFromJSONTyped(json, false);
}

export function InventoryGetTotalCurrencyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGetTotalCurrencyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': !exists(json, 'total') ? undefined : json['total'],
        'total64': !exists(json, 'total_64') ? undefined : json['total_64'],
    };
}

export function InventoryGetTotalCurrencyResponseToJSON(value?: InventoryGetTotalCurrencyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'total_64': value.total64,
    };
}

