/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryCurrencyConversion } from './InventoryCurrencyConversion';
import {
    InventoryCurrencyConversionFromJSON,
    InventoryCurrencyConversionFromJSONTyped,
    InventoryCurrencyConversionToJSON,
} from './InventoryCurrencyConversion';

/**
 * 
 * @export
 * @interface InventoryGetCurrencyConversionsResponse
 */
export interface InventoryGetCurrencyConversionsResponse {
    /**
     * Currency conversions
     * @type {Array<InventoryCurrencyConversion>}
     * @memberof InventoryGetCurrencyConversionsResponse
     */
    conversions?: Array<InventoryCurrencyConversion>;
}

/**
 * Check if a given object implements the InventoryGetCurrencyConversionsResponse interface.
 */
export function instanceOfInventoryGetCurrencyConversionsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGetCurrencyConversionsResponseFromJSON(json: any): InventoryGetCurrencyConversionsResponse {
    return InventoryGetCurrencyConversionsResponseFromJSONTyped(json, false);
}

export function InventoryGetCurrencyConversionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGetCurrencyConversionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conversions': !exists(json, 'conversions') ? undefined : ((json['conversions'] as Array<any>).map(InventoryCurrencyConversionFromJSON)),
    };
}

export function InventoryGetCurrencyConversionsResponseToJSON(value?: InventoryGetCurrencyConversionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conversions': value.conversions === undefined ? undefined : ((value.conversions as Array<any>).map(InventoryCurrencyConversionToJSON)),
    };
}

