/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryUnlockCostType } from './InventoryUnlockCostType';
import {
    InventoryUnlockCostTypeFromJSON,
    InventoryUnlockCostTypeFromJSONTyped,
    InventoryUnlockCostTypeToJSON,
} from './InventoryUnlockCostType';

/**
 * 
 * @export
 * @interface InventoryUnlockKey
 */
export interface InventoryUnlockKey {
    /**
     * Name of the item/currency/trackable_energy
     * @type {string}
     * @memberof InventoryUnlockKey
     */
    name: string;
    /**
     * 
     * @type {InventoryUnlockCostType}
     * @memberof InventoryUnlockKey
     */
    type: InventoryUnlockCostType;
}

/**
 * Check if a given object implements the InventoryUnlockKey interface.
 */
export function instanceOfInventoryUnlockKey(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function InventoryUnlockKeyFromJSON(json: any): InventoryUnlockKey {
    return InventoryUnlockKeyFromJSONTyped(json, false);
}

export function InventoryUnlockKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryUnlockKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': InventoryUnlockCostTypeFromJSON(json['type']),
    };
}

export function InventoryUnlockKeyToJSON(value?: InventoryUnlockKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': InventoryUnlockCostTypeToJSON(value.type),
    };
}

