/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryConsumeItemResponse
 */
export interface InventoryConsumeItemResponse {
    /**
     * Id of the item present in user inventory
     * @type {string}
     * @memberof InventoryConsumeItemResponse
     */
    instanceId?: string;
    /**
     * Timestamp of the last time the item was consumed
     * @type {string}
     * @memberof InventoryConsumeItemResponse
     */
    lastConsumedAt?: string;
    /**
     * Number of remaining uses for the user inventory item
     * @type {number}
     * @memberof InventoryConsumeItemResponse
     */
    remainingUses?: number;
}

/**
 * Check if a given object implements the InventoryConsumeItemResponse interface.
 */
export function instanceOfInventoryConsumeItemResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryConsumeItemResponseFromJSON(json: any): InventoryConsumeItemResponse {
    return InventoryConsumeItemResponseFromJSONTyped(json, false);
}

export function InventoryConsumeItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryConsumeItemResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instanceId': !exists(json, 'instance_id') ? undefined : json['instance_id'],
        'lastConsumedAt': !exists(json, 'last_consumed_at') ? undefined : json['last_consumed_at'],
        'remainingUses': !exists(json, 'remaining_uses') ? undefined : json['remaining_uses'],
    };
}

export function InventoryConsumeItemResponseToJSON(value?: InventoryConsumeItemResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instance_id': value.instanceId,
        'last_consumed_at': value.lastConsumedAt,
        'remaining_uses': value.remainingUses,
    };
}

