/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryGetUsersResponse
 */
export interface InventoryGetUsersResponse {
    /**
     * Total number of users that have the item
     * @type {number}
     * @memberof InventoryGetUsersResponse
     */
    totalCount?: number;
    /**
     * User ids that have the item
     * @type {Array<string>}
     * @memberof InventoryGetUsersResponse
     */
    userIds?: Array<string>;
}

/**
 * Check if a given object implements the InventoryGetUsersResponse interface.
 */
export function instanceOfInventoryGetUsersResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGetUsersResponseFromJSON(json: any): InventoryGetUsersResponse {
    return InventoryGetUsersResponseFromJSONTyped(json, false);
}

export function InventoryGetUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGetUsersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalCount': !exists(json, 'total_count') ? undefined : json['total_count'],
        'userIds': !exists(json, 'user_ids') ? undefined : json['user_ids'],
    };
}

export function InventoryGetUsersResponseToJSON(value?: InventoryGetUsersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_count': value.totalCount,
        'user_ids': value.userIds,
    };
}

