/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryGrantedItem
 */
export interface InventoryGrantedItem {
    /**
     * Count of the item after granting
     * @type {number}
     * @memberof InventoryGrantedItem
     */
    afterCount?: number;
    /**
     * Count of the item before granting
     * @type {number}
     * @memberof InventoryGrantedItem
     */
    beforeCount?: number;
    /**
     * Name of the item granted
     * @type {string}
     * @memberof InventoryGrantedItem
     */
    catalogItemName?: string;
    /**
     * Instance ids of the item granted
     * @type {Array<string>}
     * @memberof InventoryGrantedItem
     */
    instanceIds?: Array<string>;
}

/**
 * Check if a given object implements the InventoryGrantedItem interface.
 */
export function instanceOfInventoryGrantedItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGrantedItemFromJSON(json: any): InventoryGrantedItem {
    return InventoryGrantedItemFromJSONTyped(json, false);
}

export function InventoryGrantedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGrantedItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'afterCount': !exists(json, 'after_count') ? undefined : json['after_count'],
        'beforeCount': !exists(json, 'before_count') ? undefined : json['before_count'],
        'catalogItemName': !exists(json, 'catalog_item_name') ? undefined : json['catalog_item_name'],
        'instanceIds': !exists(json, 'instance_ids') ? undefined : json['instance_ids'],
    };
}

export function InventoryGrantedItemToJSON(value?: InventoryGrantedItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'after_count': value.afterCount,
        'before_count': value.beforeCount,
        'catalog_item_name': value.catalogItemName,
        'instance_ids': value.instanceIds,
    };
}

