/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryGrantedTrackablesXp
 */
export interface InventoryGrantedTrackablesXp {
    /**
     * XP of the user after granting
     * @type {number}
     * @memberof InventoryGrantedTrackablesXp
     */
    afterXp?: number;
    /**
     * XP of the user before granting
     * @type {number}
     * @memberof InventoryGrantedTrackablesXp
     */
    beforeXp?: number;
    /**
     * Number of levels progressed
     * @type {number}
     * @memberof InventoryGrantedTrackablesXp
     */
    numLevelsProgressed?: number;
    /**
     * Name of the trackable xp granted
     * @type {string}
     * @memberof InventoryGrantedTrackablesXp
     */
    trackableXpName?: string;
}

/**
 * Check if a given object implements the InventoryGrantedTrackablesXp interface.
 */
export function instanceOfInventoryGrantedTrackablesXp(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryGrantedTrackablesXpFromJSON(json: any): InventoryGrantedTrackablesXp {
    return InventoryGrantedTrackablesXpFromJSONTyped(json, false);
}

export function InventoryGrantedTrackablesXpFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryGrantedTrackablesXp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'afterXp': !exists(json, 'after_xp') ? undefined : json['after_xp'],
        'beforeXp': !exists(json, 'before_xp') ? undefined : json['before_xp'],
        'numLevelsProgressed': !exists(json, 'num_levels_progressed') ? undefined : json['num_levels_progressed'],
        'trackableXpName': !exists(json, 'trackable_xp_name') ? undefined : json['trackable_xp_name'],
    };
}

export function InventoryGrantedTrackablesXpToJSON(value?: InventoryGrantedTrackablesXp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'after_xp': value.afterXp,
        'before_xp': value.beforeXp,
        'num_levels_progressed': value.numLevelsProgressed,
        'trackable_xp_name': value.trackableXpName,
    };
}

