/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryUserInventoryItem } from './InventoryUserInventoryItem';
import {
    InventoryUserInventoryItemFromJSON,
    InventoryUserInventoryItemFromJSONTyped,
    InventoryUserInventoryItemToJSON,
} from './InventoryUserInventoryItem';

/**
 * 
 * @export
 * @interface InventoryUserInventory
 */
export interface InventoryUserInventory {
    /**
     * 
     * @type {Array<InventoryUserInventoryItem>}
     * @memberof InventoryUserInventory
     */
    items?: Array<InventoryUserInventoryItem>;
}

/**
 * Check if a given object implements the InventoryUserInventory interface.
 */
export function instanceOfInventoryUserInventory(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryUserInventoryFromJSON(json: any): InventoryUserInventory {
    return InventoryUserInventoryFromJSONTyped(json, false);
}

export function InventoryUserInventoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryUserInventory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(InventoryUserInventoryItemFromJSON)),
    };
}

export function InventoryUserInventoryToJSON(value?: InventoryUserInventory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(InventoryUserInventoryItemToJSON)),
    };
}

