/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryAppliedDiscounts
 */
export interface InventoryAppliedDiscounts {
    /**
     * List of applied discount ids
     * @type {Array<string>}
     * @memberof InventoryAppliedDiscounts
     */
    discountNames?: Array<string>;
    /**
     * Price after applying discounts
     * @type {number}
     * @memberof InventoryAppliedDiscounts
     */
    priceAfterDiscounts?: number;
}

/**
 * Check if a given object implements the InventoryAppliedDiscounts interface.
 */
export function instanceOfInventoryAppliedDiscounts(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventoryAppliedDiscountsFromJSON(json: any): InventoryAppliedDiscounts {
    return InventoryAppliedDiscountsFromJSONTyped(json, false);
}

export function InventoryAppliedDiscountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryAppliedDiscounts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discountNames': !exists(json, 'discount_names') ? undefined : json['discount_names'],
        'priceAfterDiscounts': !exists(json, 'price_after_discounts') ? undefined : json['price_after_discounts'],
    };
}

export function InventoryAppliedDiscountsToJSON(value?: InventoryAppliedDiscounts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discount_names': value.discountNames,
        'price_after_discounts': value.priceAfterDiscounts,
    };
}

