/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventorySubInventory
 */
export interface InventorySubInventory {
    /**
     * True if this item is a sub-inventory
     * @type {boolean}
     * @memberof InventorySubInventory
     */
    isSubInventory?: boolean;
}

/**
 * Check if a given object implements the InventorySubInventory interface.
 */
export function instanceOfInventorySubInventory(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InventorySubInventoryFromJSON(json: any): InventorySubInventory {
    return InventorySubInventoryFromJSONTyped(json, false);
}

export function InventorySubInventoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventorySubInventory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isSubInventory': !exists(json, 'is_sub_inventory') ? undefined : json['is_sub_inventory'],
    };
}

export function InventorySubInventoryToJSON(value?: InventorySubInventory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_sub_inventory': value.isSubInventory,
    };
}

