/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoveItemsToSubInventoryRequest
 */
export interface MoveItemsToSubInventoryRequest {
    /**
     * Ids of the items to move into the sub-inventory
     * @type {Array<string>}
     * @memberof MoveItemsToSubInventoryRequest
     */
    itemInstanceIds: Array<string>;
    /**
     * Id of the sub-inventory instance to move the item into
     * @type {string}
     * @memberof MoveItemsToSubInventoryRequest
     */
    subInventoryInstanceId: string;
}

/**
 * Check if a given object implements the MoveItemsToSubInventoryRequest interface.
 */
export function instanceOfMoveItemsToSubInventoryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "itemInstanceIds" in value;
    isInstance = isInstance && "subInventoryInstanceId" in value;

    return isInstance;
}

export function MoveItemsToSubInventoryRequestFromJSON(json: any): MoveItemsToSubInventoryRequest {
    return MoveItemsToSubInventoryRequestFromJSONTyped(json, false);
}

export function MoveItemsToSubInventoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveItemsToSubInventoryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemInstanceIds': json['item_instance_ids'],
        'subInventoryInstanceId': json['sub_inventory_instance_id'],
    };
}

export function MoveItemsToSubInventoryRequestToJSON(value?: MoveItemsToSubInventoryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_instance_ids': value.itemInstanceIds,
        'sub_inventory_instance_id': value.subInventoryInstanceId,
    };
}

