/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryUnlockKey } from './InventoryUnlockKey';
import {
    InventoryUnlockKeyFromJSON,
    InventoryUnlockKeyFromJSONTyped,
    InventoryUnlockKeyToJSON,
} from './InventoryUnlockKey';

/**
 * 
 * @export
 * @interface OpenContainerRequest
 */
export interface OpenContainerRequest {
    /**
     * Escrow id for the result, if it was evaluated already
     * @type {string}
     * @memberof OpenContainerRequest
     */
    escrowId?: string;
    /**
     * Id of the sub-inventory instance to grant into
     * @type {string}
     * @memberof OpenContainerRequest
     */
    subInventoryInstanceId?: string;
    /**
     * 
     * @type {InventoryUnlockKey}
     * @memberof OpenContainerRequest
     */
    unlockCost?: InventoryUnlockKey;
}

/**
 * Check if a given object implements the OpenContainerRequest interface.
 */
export function instanceOfOpenContainerRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OpenContainerRequestFromJSON(json: any): OpenContainerRequest {
    return OpenContainerRequestFromJSONTyped(json, false);
}

export function OpenContainerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenContainerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'escrowId': !exists(json, 'escrow_id') ? undefined : json['escrow_id'],
        'subInventoryInstanceId': !exists(json, 'sub_inventory_instance_id') ? undefined : json['sub_inventory_instance_id'],
        'unlockCost': !exists(json, 'unlock_cost') ? undefined : InventoryUnlockKeyFromJSON(json['unlock_cost']),
    };
}

export function OpenContainerRequestToJSON(value?: OpenContainerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'escrow_id': value.escrowId,
        'sub_inventory_instance_id': value.subInventoryInstanceId,
        'unlock_cost': InventoryUnlockKeyToJSON(value.unlockCost),
    };
}

