/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchProfileRequest
 */
export interface PatchProfileRequest {
    /**
     * JSON representation of the profile being patched
     * @type {object}
     * @memberof PatchProfileRequest
     */
    profile: object;
}

/**
 * Check if a given object implements the PatchProfileRequest interface.
 */
export function instanceOfPatchProfileRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profile" in value;

    return isInstance;
}

export function PatchProfileRequestFromJSON(json: any): PatchProfileRequest {
    return PatchProfileRequestFromJSONTyped(json, false);
}

export function PatchProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchProfileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profile': json['profile'],
    };
}

export function PatchProfileRequestToJSON(value?: PatchProfileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profile': value.profile,
    };
}

