/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfilesSearchProfilesResponse
 */
export interface ProfilesSearchProfilesResponse {
    /**
     * Map of user IDs to their respective profiles
     * @type {{ [key: string]: object; }}
     * @memberof ProfilesSearchProfilesResponse
     */
    profiles?: { [key: string]: object; };
}

/**
 * Check if a given object implements the ProfilesSearchProfilesResponse interface.
 */
export function instanceOfProfilesSearchProfilesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfilesSearchProfilesResponseFromJSON(json: any): ProfilesSearchProfilesResponse {
    return ProfilesSearchProfilesResponseFromJSONTyped(json, false);
}

export function ProfilesSearchProfilesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesSearchProfilesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profiles': !exists(json, 'profiles') ? undefined : json['profiles'],
    };
}

export function ProfilesSearchProfilesResponseToJSON(value?: ProfilesSearchProfilesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profiles': value.profiles,
    };
}

