/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SearchFieldOperator } from './SearchFieldOperator';
import {
    SearchFieldOperatorFromJSON,
    SearchFieldOperatorFromJSONTyped,
    SearchFieldOperatorToJSON,
} from './SearchFieldOperator';

/**
 * 
 * @export
 * @interface ProfilesSearchField
 */
export interface ProfilesSearchField {
    /**
     * Key of the field to search by
     * @type {string}
     * @memberof ProfilesSearchField
     */
    key?: string;
    /**
     * 
     * @type {SearchFieldOperator}
     * @memberof ProfilesSearchField
     */
    operator?: SearchFieldOperator;
    /**
     * Value of the field to search by
     * @type {string}
     * @memberof ProfilesSearchField
     */
    value?: string;
}

/**
 * Check if a given object implements the ProfilesSearchField interface.
 */
export function instanceOfProfilesSearchField(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfilesSearchFieldFromJSON(json: any): ProfilesSearchField {
    return ProfilesSearchFieldFromJSONTyped(json, false);
}

export function ProfilesSearchFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesSearchField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'operator': !exists(json, 'operator') ? undefined : SearchFieldOperatorFromJSON(json['operator']),
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ProfilesSearchFieldToJSON(value?: ProfilesSearchField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'operator': SearchFieldOperatorToJSON(value.operator),
        'value': value.value,
    };
}

