/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfilesGetProfileResponse
 */
export interface ProfilesGetProfileResponse {
    /**
     * JSON representation of the user's profile visible to the logged in user
     * @type {object}
     * @memberof ProfilesGetProfileResponse
     */
    profile?: object;
}

/**
 * Check if a given object implements the ProfilesGetProfileResponse interface.
 */
export function instanceOfProfilesGetProfileResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfilesGetProfileResponseFromJSON(json: any): ProfilesGetProfileResponse {
    return ProfilesGetProfileResponseFromJSONTyped(json, false);
}

export function ProfilesGetProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesGetProfileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profile': !exists(json, 'profile') ? undefined : json['profile'],
    };
}

export function ProfilesGetProfileResponseToJSON(value?: ProfilesGetProfileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profile': value.profile,
    };
}

