/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfilesPatchProfileResponse
 */
export interface ProfilesPatchProfileResponse {
    /**
     * JSON representation of the user's profile after the patch
     * @type {object}
     * @memberof ProfilesPatchProfileResponse
     */
    profile?: object;
}

/**
 * Check if a given object implements the ProfilesPatchProfileResponse interface.
 */
export function instanceOfProfilesPatchProfileResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfilesPatchProfileResponseFromJSON(json: any): ProfilesPatchProfileResponse {
    return ProfilesPatchProfileResponseFromJSONTyped(json, false);
}

export function ProfilesPatchProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesPatchProfileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profile': !exists(json, 'profile') ? undefined : json['profile'],
    };
}

export function ProfilesPatchProfileResponseToJSON(value?: ProfilesPatchProfileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profile': value.profile,
    };
}

