/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProfilesGetProfileRequest } from './ProfilesGetProfileRequest';
import {
    ProfilesGetProfileRequestFromJSON,
    ProfilesGetProfileRequestFromJSONTyped,
    ProfilesGetProfileRequestToJSON,
} from './ProfilesGetProfileRequest';

/**
 * 
 * @export
 * @interface ProfilesBatchGetProfilesSingleResponse
 */
export interface ProfilesBatchGetProfilesSingleResponse {
    /**
     * 
     * @type {string}
     * @memberof ProfilesBatchGetProfilesSingleResponse
     */
    message?: string;
    /**
     * 
     * @type {ProfilesGetProfileRequest}
     * @memberof ProfilesBatchGetProfilesSingleResponse
     */
    request?: ProfilesGetProfileRequest;
    /**
     * 
     * @type {object}
     * @memberof ProfilesBatchGetProfilesSingleResponse
     */
    response?: object;
    /**
     * 
     * @type {boolean}
     * @memberof ProfilesBatchGetProfilesSingleResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the ProfilesBatchGetProfilesSingleResponse interface.
 */
export function instanceOfProfilesBatchGetProfilesSingleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfilesBatchGetProfilesSingleResponseFromJSON(json: any): ProfilesBatchGetProfilesSingleResponse {
    return ProfilesBatchGetProfilesSingleResponseFromJSONTyped(json, false);
}

export function ProfilesBatchGetProfilesSingleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesBatchGetProfilesSingleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : ProfilesGetProfileRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : json['response'],
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function ProfilesBatchGetProfilesSingleResponseToJSON(value?: ProfilesBatchGetProfilesSingleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': ProfilesGetProfileRequestToJSON(value.request),
        'response': value.response,
        'success': value.success,
    };
}

