/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProfilesBatchGetProfilesSingleResponse } from './ProfilesBatchGetProfilesSingleResponse';
import {
    ProfilesBatchGetProfilesSingleResponseFromJSON,
    ProfilesBatchGetProfilesSingleResponseFromJSONTyped,
    ProfilesBatchGetProfilesSingleResponseToJSON,
} from './ProfilesBatchGetProfilesSingleResponse';

/**
 * 
 * @export
 * @interface ProfilesBatchGetProfilesResponse
 */
export interface ProfilesBatchGetProfilesResponse {
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof ProfilesBatchGetProfilesResponse
     */
    profiles?: { [key: string]: object; };
    /**
     * List of responses for each user ID
     * @type {Array<ProfilesBatchGetProfilesSingleResponse>}
     * @memberof ProfilesBatchGetProfilesResponse
     */
    responses?: Array<ProfilesBatchGetProfilesSingleResponse>;
}

/**
 * Check if a given object implements the ProfilesBatchGetProfilesResponse interface.
 */
export function instanceOfProfilesBatchGetProfilesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfilesBatchGetProfilesResponseFromJSON(json: any): ProfilesBatchGetProfilesResponse {
    return ProfilesBatchGetProfilesResponseFromJSONTyped(json, false);
}

export function ProfilesBatchGetProfilesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesBatchGetProfilesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profiles': !exists(json, 'profiles') ? undefined : json['profiles'],
        'responses': !exists(json, 'responses') ? undefined : ((json['responses'] as Array<any>).map(ProfilesBatchGetProfilesSingleResponseFromJSON)),
    };
}

export function ProfilesBatchGetProfilesResponseToJSON(value?: ProfilesBatchGetProfilesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profiles': value.profiles,
        'responses': value.responses === undefined ? undefined : ((value.responses as Array<any>).map(ProfilesBatchGetProfilesSingleResponseToJSON)),
    };
}

