/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProfilesSearchField } from './ProfilesSearchField';
import {
    ProfilesSearchFieldFromJSON,
    ProfilesSearchFieldFromJSONTyped,
    ProfilesSearchFieldToJSON,
} from './ProfilesSearchField';

/**
 * 
 * @export
 * @interface ProfilesSearchProfilesRequest
 */
export interface ProfilesSearchProfilesRequest {
    /**
     * Maximum number of profiles to return
     * @type {number}
     * @memberof ProfilesSearchProfilesRequest
     */
    limit?: number;
    /**
     * Number of profiles to skip before returning results
     * @type {number}
     * @memberof ProfilesSearchProfilesRequest
     */
    offset?: number;
    /**
     * List of search fields to filter profiles by
     * @type {Array<ProfilesSearchField>}
     * @memberof ProfilesSearchProfilesRequest
     */
    searchFields?: Array<ProfilesSearchField>;
}

/**
 * Check if a given object implements the ProfilesSearchProfilesRequest interface.
 */
export function instanceOfProfilesSearchProfilesRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfilesSearchProfilesRequestFromJSON(json: any): ProfilesSearchProfilesRequest {
    return ProfilesSearchProfilesRequestFromJSONTyped(json, false);
}

export function ProfilesSearchProfilesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesSearchProfilesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'searchFields': !exists(json, 'search_fields') ? undefined : ((json['search_fields'] as Array<any>).map(ProfilesSearchFieldFromJSON)),
    };
}

export function ProfilesSearchProfilesRequestToJSON(value?: ProfilesSearchProfilesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'limit': value.limit,
        'offset': value.offset,
        'search_fields': value.searchFields === undefined ? undefined : ((value.searchFields as Array<any>).map(ProfilesSearchFieldToJSON)),
    };
}

