/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfilesGetProfileRequest
 */
export interface ProfilesGetProfileRequest {
    /**
     * User ID of the user who's profile is being viewed
     * @type {string}
     * @memberof ProfilesGetProfileRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the ProfilesGetProfileRequest interface.
 */
export function instanceOfProfilesGetProfileRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function ProfilesGetProfileRequestFromJSON(json: any): ProfilesGetProfileRequest {
    return ProfilesGetProfileRequestFromJSONTyped(json, false);
}

export function ProfilesGetProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesGetProfileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
    };
}

export function ProfilesGetProfileRequestToJSON(value?: ProfilesGetProfileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
    };
}

