/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SearchFieldOperator = {
    UnspecifiedOperator: 'UNSPECIFIED_OPERATOR',
    Equals: 'EQUALS',
    NotEquals: 'NOT_EQUALS',
    Contains: 'CONTAINS'
} as const;
export type SearchFieldOperator = typeof SearchFieldOperator[keyof typeof SearchFieldOperator];


export function SearchFieldOperatorFromJSON(json: any): SearchFieldOperator {
    return SearchFieldOperatorFromJSONTyped(json, false);
}

export function SearchFieldOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchFieldOperator {
    return json as SearchFieldOperator;
}

export function SearchFieldOperatorToJSON(value?: SearchFieldOperator | null): any {
    return value as any;
}

