/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InventoryUnlockKey } from './InventoryUnlockKey';
import {
    InventoryUnlockKeyFromJSON,
    InventoryUnlockKeyFromJSONTyped,
    InventoryUnlockKeyToJSON,
} from './InventoryUnlockKey';

/**
 * 
 * @export
 * @interface UnlockContainerRequest
 */
export interface UnlockContainerRequest {
    /**
     * 
     * @type {InventoryUnlockKey}
     * @memberof UnlockContainerRequest
     */
    unlockCost?: InventoryUnlockKey;
}

/**
 * Check if a given object implements the UnlockContainerRequest interface.
 */
export function instanceOfUnlockContainerRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UnlockContainerRequestFromJSON(json: any): UnlockContainerRequest {
    return UnlockContainerRequestFromJSONTyped(json, false);
}

export function UnlockContainerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnlockContainerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unlockCost': !exists(json, 'unlock_cost') ? undefined : InventoryUnlockKeyFromJSON(json['unlock_cost']),
    };
}

export function UnlockContainerRequestToJSON(value?: UnlockContainerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'unlock_cost': InventoryUnlockKeyToJSON(value.unlockCost),
    };
}

