/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserItemMetadataRequest
 */
export interface UpdateUserItemMetadataRequest {
    /**
     * Metadata to be attached to user inventory item. Not be confused with metadata with catalog item
     * @type {object}
     * @memberof UpdateUserItemMetadataRequest
     */
    metadata?: object;
}

/**
 * Check if a given object implements the UpdateUserItemMetadataRequest interface.
 */
export function instanceOfUpdateUserItemMetadataRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserItemMetadataRequestFromJSON(json: any): UpdateUserItemMetadataRequest {
    return UpdateUserItemMetadataRequestFromJSONTyped(json, false);
}

export function UpdateUserItemMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserItemMetadataRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function UpdateUserItemMetadataRequestToJSON(value?: UpdateUserItemMetadataRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': value.metadata,
    };
}

