/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertProfileRequest
 */
export interface UpsertProfileRequest {
    /**
     * JSON representation of the profile being upserted
     * @type {object}
     * @memberof UpsertProfileRequest
     */
    profile: object;
}

/**
 * Check if a given object implements the UpsertProfileRequest interface.
 */
export function instanceOfUpsertProfileRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profile" in value;

    return isInstance;
}

export function UpsertProfileRequestFromJSON(json: any): UpsertProfileRequest {
    return UpsertProfileRequestFromJSONTyped(json, false);
}

export function UpsertProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertProfileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profile': json['profile'],
    };
}

export function UpsertProfileRequestToJSON(value?: UpsertProfileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profile': value.profile,
    };
}

